# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(612, 453)
        self.gridLayout = QtWidgets.QGridLayout(Main)
        self.gridLayout.setObjectName("gridLayout")
        self.CardWidget = CardWidget(Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget.sizePolicy().hasHeightForWidth())
        self.CardWidget.setSizePolicy(sizePolicy)
        self.CardWidget.setObjectName("CardWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.CardWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frameview = ImageLabel(self.CardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameview.sizePolicy().hasHeightForWidth())
        self.frameview.setSizePolicy(sizePolicy)
        self.frameview.setObjectName("frameview")
        self.gridLayout_3.addWidget(self.frameview, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.CardWidget, 0, 0, 1, 2)
        self.CardWidget_2 = CardWidget(Main)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.CardWidget_2)
        self.gridLayout_2.setHorizontalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.helpPlainTextEdit = PlainTextEdit(self.CardWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpPlainTextEdit.sizePolicy().hasHeightForWidth())
        self.helpPlainTextEdit.setSizePolicy(sizePolicy)
        self.helpPlainTextEdit.setMinimumSize(QtCore.QSize(0, 215))
        self.helpPlainTextEdit.setReadOnly(True)
        self.helpPlainTextEdit.setObjectName("helpPlainTextEdit")
        self.gridLayout_2.addWidget(self.helpPlainTextEdit, 0, 7, 3, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 1, 1, 1)
        self.BodyLabel_2 = BodyLabel(self.CardWidget_2)
        self.BodyLabel_2.setText("")
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.gridLayout_2.addWidget(self.BodyLabel_2, 2, 5, 1, 1)
        self.HeaderCardWidget = HeaderCardWidget(self.CardWidget_2)
        self.HeaderCardWidget.setObjectName("HeaderCardWidget")
        self.gridLayout_2.addWidget(self.HeaderCardWidget, 0, 0, 3, 1)
        self.sysButton = PushButton(self.CardWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sysButton.sizePolicy().hasHeightForWidth())
        self.sysButton.setSizePolicy(sizePolicy)
        self.sysButton.setObjectName("sysButton")
        self.gridLayout_2.addWidget(self.sysButton, 1, 1, 1, 6)
        self.tra1RadioButton = RadioButton(self.CardWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tra1RadioButton.sizePolicy().hasHeightForWidth())
        self.tra1RadioButton.setSizePolicy(sizePolicy)
        self.tra1RadioButton.setChecked(True)
        self.tra1RadioButton.setObjectName("tra1RadioButton")
        self.gridLayout_2.addWidget(self.tra1RadioButton, 2, 2, 1, 1)
        self.BodyLabel = BodyLabel(self.CardWidget_2)
        self.BodyLabel.setText("")
        self.BodyLabel.setObjectName("BodyLabel")
        self.gridLayout_2.addWidget(self.BodyLabel, 0, 5, 1, 1)
        self.tra2RadioButton = RadioButton(self.CardWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tra2RadioButton.sizePolicy().hasHeightForWidth())
        self.tra2RadioButton.setSizePolicy(sizePolicy)
        self.tra2RadioButton.setObjectName("tra2RadioButton")
        self.gridLayout_2.addWidget(self.tra2RadioButton, 2, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 2, 4, 1, 1)
        self.gridLayout.addWidget(self.CardWidget_2, 1, 0, 1, 2)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Main"))
        self.sysButton.setText(_translate("Main", "一键启动系统"))
        self.tra1RadioButton.setText(_translate("Main", "追踪策略一"))
        self.tra2RadioButton.setText(_translate("Main", "追踪策略二"))
from qfluentwidgets import BodyLabel, CardWidget, HeaderCardWidget, ImageLabel, PlainTextEdit, PushButton, RadioButton
