# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(612, 453)
        self.gridLayout = QtWidgets.QGridLayout(Main)
        self.gridLayout.setObjectName("gridLayout")
        self.CardWidget = CardWidget(Main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CardWidget.sizePolicy().hasHeightForWidth())
        self.CardWidget.setSizePolicy(sizePolicy)
        self.CardWidget.setObjectName("CardWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.CardWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frameview = ImageLabel(self.CardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameview.sizePolicy().hasHeightForWidth())
        self.frameview.setSizePolicy(sizePolicy)
        self.frameview.setObjectName("frameview")
        self.gridLayout_3.addWidget(self.frameview, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.CardWidget, 0, 0, 1, 2)
        self.CardWidget_2 = CardWidget(Main)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.CardWidget_2)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(8)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sysButton = PillPushButton(self.CardWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sysButton.sizePolicy().hasHeightForWidth())
        self.sysButton.setSizePolicy(sizePolicy)
        self.sysButton.setMinimumSize(QtCore.QSize(200, 70))
        self.sysButton.setObjectName("sysButton")
        self.gridLayout_2.addWidget(self.sysButton, 2, 1, 1, 1)
        self.helpPlainTextEdit = PlainTextEdit(self.CardWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpPlainTextEdit.sizePolicy().hasHeightForWidth())
        self.helpPlainTextEdit.setSizePolicy(sizePolicy)
        self.helpPlainTextEdit.setMinimumSize(QtCore.QSize(0, 215))
        self.helpPlainTextEdit.setReadOnly(True)
        self.helpPlainTextEdit.setObjectName("helpPlainTextEdit")
        self.gridLayout_2.addWidget(self.helpPlainTextEdit, 1, 2, 3, 1)
        self.HeaderCardWidget = HeaderCardWidget(self.CardWidget_2)
        self.HeaderCardWidget.setObjectName("HeaderCardWidget")
        self.gridLayout_2.addWidget(self.HeaderCardWidget, 1, 0, 3, 1)
        self.gridLayout.addWidget(self.CardWidget_2, 1, 0, 1, 2)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Main"))
        self.sysButton.setText(_translate("Main", "一键启动系统"))
from qfluentwidgets import CardWidget, HeaderCardWidget, ImageLabel, PillPushButton, PlainTextEdit
